<?php

if ( !defined( 'MEDIAWIKI' ) ) {
	die( 'This file is a MediaWiki extension, it is not a valid entry point' );
}

use MediaWiki\MediaWikiServices;
use MediaWiki\Title\Title;

global $wgAutoLlmsTxt, $wgServer, $wgCanonicalServer;
if ( !isset( $wgAutoLlmsTxt['server'] ) ) {
	$wgAutoLlmsTxt['server'] = isset( $wgCanonicalServer ) ? $wgCanonicalServer : $wgServer;
}

if ( !isset( $wgAutoLlmsTxt['index_filename'] ) ) {
	$wgAutoLlmsTxt['index_filename'] = 'llms.txt';
}
if ( !isset( $wgAutoLlmsTxt['full_filename'] ) ) {
	$wgAutoLlmsTxt['full_filename'] = 'llms-full.txt';
}
if ( !isset( $wgAutoLlmsTxt['exclude_namespaces'] ) ) {
	$wgAutoLlmsTxt['exclude_namespaces'] = [
		NS_TALK,
		NS_USER,
		NS_USER_TALK,
		NS_PROJECT_TALK,
		NS_FILE,
		NS_FILE_TALK,
		NS_MEDIAWIKI,
		NS_MEDIAWIKI_TALK,
		NS_TEMPLATE,
		NS_TEMPLATE_TALK,
		NS_HELP,
		NS_HELP_TALK,
		NS_CATEGORY,
		NS_CATEGORY_TALK,
	];
}
if ( !isset( $wgAutoLlmsTxt['exclude_pages'] ) ) {
	$wgAutoLlmsTxt['exclude_pages'] = [];
}
if ( !isset( $wgAutoLlmsTxt['max_entries'] ) ) {
	$wgAutoLlmsTxt['max_entries'] = 50000;
}
if ( !isset( $wgAutoLlmsTxt['max_bytes'] ) ) {
	$wgAutoLlmsTxt['max_bytes'] = 50000000;
}
if ( !isset( $wgAutoLlmsTxt['summary_length'] ) ) {
	$wgAutoLlmsTxt['summary_length'] = 320;
}
if ( !isset( $wgAutoLlmsTxt['header'] ) ) {
	$wgAutoLlmsTxt['header'] = "# llms.txt\n\nGenerated by AutoLlmsTxt for MediaWiki.\n";
}
if ( !isset( $wgAutoLlmsTxt['footer'] ) ) {
	$wgAutoLlmsTxt['footer'] = "\n";
}
if ( !isset( $wgAutoLlmsTxt['min_age'] ) ) {
	$wgAutoLlmsTxt['min_age'] = 0;
}

class AutoLlmsTxt {
	public static function writeLlmsFiles() {
		global $wgAutoLlmsTxt;

		$min_age = $wgAutoLlmsTxt['min_age'];
		$indexFile = $wgAutoLlmsTxt['index_filename'];
		$fullFile = $wgAutoLlmsTxt['full_filename'];

		$indexMtime = file_exists( $indexFile ) ? filemtime( $indexFile ) : false;
		$fullMtime = file_exists( $fullFile ) ? filemtime( $fullFile ) : false;
		$newestMtime = max( $indexMtime ?: 0, $fullMtime ?: 0 );
		if ( $newestMtime !== 0 && time() - $newestMtime < $min_age ) {
			return;
		}

		$dbr = MediaWikiServices::getInstance()->getDBLoadBalancer()->getConnection( DB_REPLICA );
		$res = $dbr->query( self::getSQL() );

		$indexTmp = $indexFile . '.tmp' . bin2hex( random_bytes( 16 ) ) . '.tmp';
		$fullTmp = $fullFile . '.tmp' . bin2hex( random_bytes( 16 ) ) . '.tmp';

		$indexHandle = fopen( $indexTmp, 'w' );
		$fullHandle = fopen( $fullTmp, 'w' );
		if ( $indexHandle === false || $fullHandle === false ) {
			error_log( 'AutoLlmsTxt: unable to open temporary output files.' );
			return;
		}

		$entries = 0;
		$bytes = 0;
		$error = false;

		try {
			$bytes += self::write( $indexHandle, $wgAutoLlmsTxt['header'] );
			$bytes += self::write( $fullHandle, str_replace( '# llms.txt', '# llms-full.txt', $wgAutoLlmsTxt['header'] ) );
			while ( $row = $res->fetchObject() ) {
				$entries++;
				$line = self::formatIndexLine( $row );
				$detail = self::formatFullLine( $row );
				$bytes += self::write( $indexHandle, $line );
				$bytes += self::write( $fullHandle, $detail );
				if ( $entries >= $wgAutoLlmsTxt['max_entries'] || $bytes >= $wgAutoLlmsTxt['max_bytes'] ) {
					break;
				}
			}
			$bytes += self::write( $indexHandle, $wgAutoLlmsTxt['footer'] );
			$bytes += self::write( $fullHandle, $wgAutoLlmsTxt['footer'] );
		} catch ( Exception $e ) {
			error_log( 'AutoLlmsTxt writing failed: ' . $e->getMessage() );
			$error = true;
		} finally {
			fclose( $indexHandle );
			fclose( $fullHandle );
		}

		if ( $error ) {
			@unlink( $indexTmp );
			@unlink( $fullTmp );
			return;
		}

		rename( $indexTmp, $indexFile );
		rename( $fullTmp, $fullFile );
	}

	private static function getSQL() {
		global $wgAutoLlmsTxt;
		$dbr = MediaWikiServices::getInstance()->getDBLoadBalancer()->getConnection( DB_REPLICA );
		$page = $dbr->tableName( 'page' );
		$revision = $dbr->tableName( 'revision' );
		$sql = "SELECT page_id AS id, page_namespace AS namespace, page_title AS title, MAX(rev_timestamp) AS last_modification FROM $page, $revision WHERE page_is_redirect = 0 AND rev_page = page_id ";
		if ( is_array( $wgAutoLlmsTxt['exclude_namespaces'] ) && count( $wgAutoLlmsTxt['exclude_namespaces'] ) > 0 ) {
			$sql .= 'AND page_namespace NOT IN (' . implode( ',', $wgAutoLlmsTxt['exclude_namespaces'] ) . ') ';
		}
		if ( is_array( $wgAutoLlmsTxt['exclude_pages'] ) && count( $wgAutoLlmsTxt['exclude_pages'] ) > 0 ) {
			$sql .= "AND page_title NOT IN ('" . implode( "','", $wgAutoLlmsTxt['exclude_pages'] ) . "') ";
		}
		$sql .= 'GROUP BY page_id ORDER BY MAX(rev_timestamp) DESC';
		return $sql;
	}

	private static function formatIndexLine( $result ) {
		global $wgAutoLlmsTxt;
		$title = Title::makeTitle( $result->namespace, $result->title );
		$url = $wgAutoLlmsTxt['server'] . $title->getLocalURL();
		$display = str_replace( '_', ' ', $result->title );
		return '- [' . $display . '](' . $url . ")\n";
	}

	private static function formatFullLine( $result ) {
		global $wgAutoLlmsTxt;
		$title = Title::makeTitle( $result->namespace, $result->title );
		$url = $wgAutoLlmsTxt['server'] . $title->getLocalURL();
		$display = str_replace( '_', ' ', $result->title );
		$lastmod = gmdate( 'Y-m-d\\TH:i:s\\Z', wfTimestamp( TS_UNIX, $result->last_modification ) );
		$summary = self::truncate( $display . ' page from this wiki.', $wgAutoLlmsTxt['summary_length'] );
		return "## {$display}\n- URL: {$url}\n- Last-Modified: {$lastmod}\n- Summary: {$summary}\n\n";
	}

	private static function truncate( $text, $length ) {
		if ( strlen( $text ) <= $length ) {
			return $text;
		}
		return substr( $text, 0, $length - 3 ) . '...';
	}

	private static function write( $handle, $data ) {
		$bytes = fwrite( $handle, $data );
		if ( $bytes === false || $bytes === 0 ) {
			throw new Exception( 'fwrite failed.' );
		}
		return $bytes;
	}
}
